server:
  port: 8003
mybatis:
  type-aliases-package: com.example.pojo
  mapper-locations: classpath:/com/example/*.xml

spring:
  application:
    name: provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 575827443

# Eureka的配置：服务注册到哪里
eureka:
  client:
    service-url: # 就是在eureka那里的url地址
      defaultZone: http://localhost:7002/eureka/
      #defaultZone: http://localhost:7001/eureka/,http://e1:7002/eureka/,http://e2:7003/eureka/
  instance:
    instance-id: provider3 #修改默认描述信息

# info配置
info:
  app.name: springcloud-test
  company.name:

